name: scotty-web
version: 0.1.0.0
github: "githubuser/scotty-web"
license: BSD-3-Clause
author: "Kavin J S"
maintainer: "kavinjs21@gmail.com"
copyright: "2026 Kavin J S"

extra-source-files:
  - README.md
  - CHANGELOG.md

description: Please see the README on GitHub

dependencies:
  - base >= 4.7 && < 5
  - scotty
  - text
  - bytestring
  - process
  - directory         

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields

executables:
  scotty-web-exe:
    main: Web.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - scotty
      - text
      - bytestring
      - process
      - directory   